treats/__init__.py
from datetime import datetime, timedelta
from flask import Flask, g, session, render_template, make_response
from flask_bootstrap import Bootstrap

app = Flask(__name__)


if __name__ == '__main__':
	#app.run()
  app.run(host='0.0.0.0', debug=True)

treats/views/contact.py
# -*- coding: utf-8 -*-
from flask import Blueprint, abort, flash, g, jsonify, redirect, \
	render_template, request, url_for


contact = Blueprint('contact', __name__, url_prefix='/contact')

@contact.route('/')
def index():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/contact.html', title='Enquire Now')

treats/views/main.py
# -*- coding: utf-8 -*-
from flask import Blueprint, abort, flash, g, jsonify, redirect, \
	render_template, request, url_for


main = Blueprint('main', __name__, url_prefix='/')

@main.route('/')
def index():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/index.html', title='Home')


@main.route('/invitation')
def invitation():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/invitation.html', title='Our Invitation')


@main.route('/food')
def food():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/food.html', title='Food Page')

@main.route('/about_us')
def about():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/about.html', title='Alex Wedlock')

@main.route('/yoga')
def yoga():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/yoga.html', title='Food Page')

@main.route('/location')
def location():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/location.html', title='Our Location')

@main.route('/what_you_can_expect')
def exp():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/expect.html', title='What You Can Expect')

@main.route('/programme')
def programme():

	#posts = Blog.query.order_by(desc(Blog.id)).limit(3)


	return render_template('/programme.html', title='Our Programme')

treats/templates/__layout__.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome 4.7.0 -->

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" media="screen">
    
    <!-- Main style -->

    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet" media="screen">

    <link href="{{ url_for('static', filename='css/style2.css') }}" rel="stylesheet" media="screen">


    <!-- Optional JavaScript -->
    <script src="{{url_for('static', filename='js/lazysizes.min.js') }}"></script>

    <script src="{{url_for('static', filename='js/jquery.min.js') }}"></script>

    <script src="{{url_for('static', filename='js/fun.js') }}"></script>


    <link rel="shortcut icon" href="/favicon-pelot.ico" type="image/x-icon" />
    
    <link rel="canonical" href="#">

    <meta name="description" content="#.">
    <meta name="twitter:card" content="summary">
    <meta property="og:type" content="article">

    {% if title %}
        <title>PSYCOTHERAPYRETREAT.COM | {{ title }}</title>
    {% else %}
        <title>PSYCOTHERAPYRETREAT.COM</title>
    {% endif %}

    
    
</head>
<body class="home-page headerburgernav  contains-header">
    <div class="skip"><a href="#main-content" class="offscreen">Skip to content</a></div>
    
<nav id="nav">
    <div class="container">
        <a class="nav-icon" aria-label="Menu" title="Menu"><i class="fa fa-bars fa-3x" aria-hidden="true"></i><span>Menu</span></a>
        <a href="/" title="" class="logo" data-sticky=""><img src="/static/img/logo.png" alt="" /></a>
            <ul class="primary-nav">
                    <li class="home">
                        <a href="/" class="text-link">Home</a>
                    </li>
                    <li class="invite">
                        <a href="{{ url_for('main.invitation') }}" class="text-link">Our Invitaion</a>
                    </li>
                    <li class="food">
                        <a href="{{ url_for('main.food') }}" class="text-link">Food</a>
                    </li>
                    <li class="yoga">
                        <a href="{{ url_for('main.yoga') }}" class="text-link">Yoga</a>
                    </li>
                    <li class="exp">
                        <a href="{{ url_for('main.exp') }}" class="text-link">What you can expect</a>
                    </li>
                    <li class="location">
                        <a href="{{ url_for('main.location') }}" class="text-link">The Location</a>
                    </li>
                    <li class="about_us">
                        <a href="{{ url_for('main.about') }}" class="text-link">About Us</a>
                    </li>
                    <li class="the_programme">
                        <a href="{{ url_for('main.programme') }}" class="text-link">Programme</a>
                    </li>
                    <li class="latest_news">
                          <a href="/programmes/" class="text-link">Latest News</a>
                    </li>
                     <li class="book_now">
                          <a href="/programmes/" class="text-link">Book Now</a>
                    </li>


            </ul>            
                <ul class="primary-cta">
                    <li><a href="{{ url_for('contact.index') }}" class="btn">Enquire Now</a></li>
                </ul>
    </div>
</nav>


    <main id="main-content">


            {% block content %}{% endblock content %}









<footer id="footer">
    <div class="container">
        <div class="row">


                <div class="col-lg-3 col-md-8 lg-pt-30">

    <div class="phone-number">
        <span><a href="tel:+330642075132">+44 78 10 44 64 96</a></span>
    </div>
                                            <p class="email">PSYCOTHERAPYRETREAT.COM </p>
                </div>

            <nav class="col-lg-9 col-md-8 lg-pt-30">
                <ul class="footer-nav">
                        <li class=""><a href="/" class="text-link">Home</a></li>
                        <li class=""><a href="{{ url_for('main.about') }}" class="text-link">About Us</a></li>
                        <li class=""><a href="{{ url_for('main.programme') }}" class="text-link">Programmes</a></li>
                        <li class=""><a href="#" class="text-link">Latest News</a></li>
                        <li class=""><a href="{{ url_for('contact.index') }}" class="text-link">Enquire</a></li>
                </ul>
            </nav>


        </div>        

        <div class="row lg-pt-20">
            <div class="col-lg-6 col-md-12 pt-20">
 <address>11 Walsingham Place, Truro,Cornwall TR1 2RP United Kingdom</address>                                                 <div id="copyright">
                    <p class="copyright">&copy; Copyright 2019 FamousMedia. All rights reserved.</p>               
                </div>
            </div>
            <div class="col-lg-6 col-md-12 pt-20">                
                <ul class="footer-logos">
                            
                </ul>
            </div>
        </div>

            <div class="row pt-10">
                <nav class="col-12 legal-nav">
                    <ul>
                            <li><a href="/privacy-policy/" class="text-link">Privacy Policy</a></li>
                            <li><a href="/cookie-policy/" class="text-link">Cookie Policy</a></li>
                    </ul>
                </nav>
            </div>
    </div>
</footer>
    

treats/templates/about.html
{% extends "__layout__.html" %}
{% block content %}
<style type="text/css">
   .article_image{
    width: 470px;
    margin-right: 40px;
}
</style>

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>Alex Wedlock</h1>

<style>

.flip-card {
  background-color: transparent;
  width: 300px;
  height: 300px;
  perspective: 1000px;
}

.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.6s;
  transform-style: preserve-3d;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}

.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
}

.flip-card-front {
  background-color: #bbb;
  color: black;
}

.flip-card-back {
  background-color: #3b8e4a;
  color: white;
  transform: rotateY(180deg);
}

h3 {
  background-color: #fff;

}
</style>
                        <center>
                        <div class="flip-card">
                          <div class="flip-card-inner">
                            <div class="flip-card-front">
                              <img src="static/img/ab.jpg" alt="Avatar" style="width:300px;height:300px;">
                            </div>
                            <div class="flip-card-back">
                                <br>
                            <h3><strong>Alex Wedlock</strong></h3> 
                              <p>Psychodynamic & Psychotherapist</p> 
                              <p><i class="fa fa-facebook-official" aria-hidden="true"></i></p>
                              <p><i class="fa fa-instagram" aria-hidden="true"></i></p>
                              <p><i class="fa fa-google-plus-official" aria-hidden="true"></i></p>
                            </div>
                          </div>
                        </div>
                        </center>
                        <br>
                        <br>

                    <p>
                        Alex is a Psychodynamic Psychotherapist. She is also qualified within the fields of
                        Neuro Linguistic Programming and Hypnotherapy. Her work is informed by
                        influences such as Sigmund Freud and Carl Jung. She has a breadth of experience
                        and runs a busy private practice in Cornwall, UK.
                        Alex is a creative therapist and used her various qualifications and training together
                        with her vast and varied experiences to design our programme so that it can be
                        used flexibly with you in mind. She is passionate about people and intrigued by how
                        we think. Alex will be delivering our programme during your stay. You can expect
                        her to meet you with her own unique blend of energy, vitality and understanding.
                        She has a straight forward and firm intention to make things feel more comfortable
                        and empower positive change.</p>

                           

            </div>
        </div>
    </div>
</div>

{% endblock content %}

treats/templates/contact.html
{% extends "__layout__.html" %}
{% block content %}

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>Enquire Now</h1>
                
                    <p>If you Have any enquire just contact us here.</p>

                <style>
                input[type=text], select, textarea {
                  width: 100%;
                  padding: 12px;
                  border: 1px solid #ccc;
                  border-radius: 4px;
                  box-sizing: border-box;
                  margin-top: 6px;
                  margin-bottom: 16px;
                  resize: vertical;
                }

                input[type=submit] {
                  background-color: #4CAF50;
                  color: white;
                  padding: 12px 20px;
                  border: none;
                  border-radius: 4px;
                  cursor: pointer;
                }

                input[type=submit]:hover {
                  background-color: #45a049;
                }


                </style>

                <div class="container">
                  <form action="/action_page.php">
                    <label for="fname">First Name</label>
                    <input type="text" id="fname" name="firstname" placeholder="Your name..">

                    <label for="lname">Last Name</label>
                    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

                    <label for="country">Country</label>
                    <select id="country" name="country">
                      <option value="australia">Australia</option>
                      <option value="canada">Canada</option>
                      <option value="usa">USA</option>
                    </select>

                    <label for="subject">Subject</label>
                    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

                    <input type="submit" value="Submit">
                  </form>
                </div>



                           

            </div>
        </div>
    </div>
</div>

{% endblock content %}

treats/templates/expect.html
{% extends "__layout__.html" %}
{% block content %}

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>What you can Expect ?</h1>
                
                    <p>
                        You can expect us to start at the beginning. We want to know when and where
                        your stresses and anxieties began, we want to understand you to your very roots!
                        Paying attention to each and every part of you and your thinking, your physical
                        body, your feelings and your expression, we will explore together how you can find
                        within yourself, confidence, harmony and peace. We will ask you to kindly share
                        your thoughts and respectfully share your feelings in order that we can establish a
                        deep understanding of your wonderful self and therefore find the road to positive
                        change. You can expect your journey to be endlessly exciting, beautifully emotional
                        and fabulously freeing. We will ensure that you travel safely and with sound
                        navigation.
                        To support you on your journey, you can relax into the gentle hospitality of Morocco
                        and enjoy its scenic riches as you watch the sun rise and then set within this
                        beautiful landscape. You can take pleasure from our comforting and flavoursome
                        food - served to you in the perfect reflective space. We will offer yoga practices and
                        massage to enhance your experience and give you the perfect opportunity for
                        relaxation and rejuvenation.
                    </p>

                           

            </div>
        </div>
    </div>
</div>

{% endblock content %}

treats/templates/food.html
{% extends "__layout__.html" %}
{% block content %}

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>Food</h1>
                
                    <p>
                        We are concerned with your wellbeing. We want you to have a wonderful, relaxing
						and enlightening stay with us. We also want you to enjoy an authentic Moroccan
						experience. We have therefore engaged talented local chefs who are committed to
						and passionate about providing the very best Moroccan feasts. Breakfast, lunch and
						dinner will be provided throughout your stay and you can expect to eat traditionally,
						enjoying the array of flavours and colours typical of a Moroccan diet. We will of
						course, tailor our menus to suit your dietary requirements. We invite you to let us
						care for you…<a class="primary_btn" href="#"> | Contact Us |</a>
                    </p>

                           

            </div>
        </div>
    </div>
</div>


{% endblock content %}

treats/templates/invitation.html
{% extends "__layout__.html" %}
{% block content %}

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>The Invitation</h1>
                
                    <p>
                        Our Invitation to you…
						You are cordially invited to join us. We invite you to relax, explore and enhance
						your thinking.
						To help you with your voyage, we will take care of you. We will welcome you to our
						tranquil location and feed you wonderful Moroccan food, sourced locally and
						prepared for you with love and kindness.
						We will bear both your wellbeing and your soul in mind.
						We will be together in this beautiful country, surrounded by colour, culture and
						everything we need to focus inward.
						And we will guide you through our unique programme which will enable your
						transformation.Together we can change your life…<a class="primary_btn" href="#"> | Contact Us |</a>
                    </p>

                           

            </div>
        </div>
    </div>
</div>

{% endblock content %}

treats/templates/location.html
{% extends "__layout__.html" %}
{% block content %}

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>The Location</h1>
                
                    <p>
                        We believe that Morocco is the perfect country for our retreat. It offers a different
                        landscape, an invitation to pause and the most wonderful cultural experience. We
                        scoured the country to find the perfect location for you. We wanted to be close to
                        the ocean to enable us to see a different horizon, we wanted to be near the sand to
                        enable us to feel a different terrain underfoot and we wanted to offer you a simple
                        yet rich backdrop to your journey alongside us. We intended to find a location
                        suitable for exploration, with the right qualities for reflection. We welcome you to
                        our Psychotherapy Retreat in Morocco. We know you will enjoy the colour, flavour
                        and essence of this magical part of Africa.</a>
                    </p>

                           

            </div>
        </div>
    </div>
</div>

{% endblock content %}

treats/templates/yoga.html
{% extends "__layout__.html" %}
{% block content %}

<div class="textcenterwide sp spb-half ">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>Yoga</h1>
                
                    <p>
                        Yoga’s ancient philosophies and benefits have been tried and tested over hundreds
						of years. We are delighted to be able to offer a daily yoga practice to support your
						retreat with us. We work with experienced and enlightened teachers and our focus
						here is on relaxation, the importance of the breath and the opportunity that yoga
						offers us to look inward. We feel that it is the perfect accompaniment to our
						programme. It is optional and certainly we have no expectation of ability. But we
						warmly invite you to join us!.<a class="primary_btn" href="#"> | Contact Us |</a>
                    </p>

                           

            </div>
        </div>
    </div>
</div>

{% endblock content %}